name: politikchart
description: 'Statistical data visualization for politics.'
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: '>=3.27.2'
  sdk: ^3.6.1

dependencies:
  collection: 1.19.0
  flutter:
    sdk: flutter
  flutter_animate: 4.5.2
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  refena_flutter: 2.1.1
  slang: 4.4.1
  slang_flutter: 4.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
