name: Deploy

on:
  push:
    branches: [main]

env:
  FLUTTER_VERSION: "3.27.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies
        run: flutter pub get

      - name: Get Current Date
        id: get-date
        run: echo "version=v$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build
        run: flutter build web --wasm --base-href="/${{ env.version }}/" --dart-define IMPRINT_STREET="${{ secrets.IMPRINT_STREET }}" --dart-define IMPRINT_CITY="${{ secrets.IMPRINT_CITY }}"

      - name: Create version directory
        run: mkdir -p build/web/${{ env.version }}

      - name: Move build files to version directory
        run: |
          shopt -s extglob
          mv build/web/!(${{ env.version }}|index.html|_headers) build/web/${{ env.version }}

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: web-result
          path: build/web

  commit:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Current Directory
        run: rm -rf ./*

      - name: Clear .github Directory
        run: rm -rf .github

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-result
          path: ./web-result

      - name: Move Build Files to Root
        run: mv ./web-result/* ./

      - name: Clean Up Temporary Directory
        run: rm -rf ./web-result

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          new_branch: deploy
          push: origin deploy --force
